### ISSUE TITLE
ERROR: Couldn't spawn NPC sage_of_light

### ISSUE THREAD

**Issue by ghost** [Zyk6870/OpenJK#7]
Hello, this is my first attempt to create a Zyk Mod server and I've just compilled this OpenJK fork including Zyk Mod and it gives a server crash right after anyone try logging into an account on `kor1`:

```
------ Server Initialization ------
Server: kor1
----- FS_Startup -----
Current search path:
/home/testzyk/.local/share/zykopenjkmod/base
./base/assets3.pk3 (16 files)
./base/assets2.pk3 (62 files)
./base/assets1.pk3 (8320 files)
./base/assets0.pk3 (15346 files)
./base
 
----------------------
23744 files in pk3 files

VM_Create: jampgamex86_64.so succeeded
------- Game Initialization -------
gamename: Zyk OpenJK Mod v3.80
gamedate: Dec 15 2020
Logging to games.log
------------------------------------------------------------
InitGame: \zyk_sv_set_default_nextmap\map_restart 0\version\JAmp: v1.0.1.0 linux-x86_64 Dec 15 2020\timelimit\0\sv_privateClients\0\sv_minRate\0\sv_minPing\0\sv_maxclients\8\sv_maxRate\0\sv_maxPing\0\sv_hostname\*Jedi*\sv_fps\40\sv_floodProtectSlow\1\sv_floodProtect\1\sv_autoDemo\0\sv_allowDownload\0\protocol\26\mapname\kor1\gamename\Zyk OpenJK Mod v3.80\g_weaponDisable\0\g_stepSlideFix\1\g_siegeTeamSwitch\1\g_siegeTeam2\none\g_siegeTeam1\none\g_saberLocking\1\g_privateDuel\1\g_noSpecMove\0\g_needpass\0\g_maxHolocronCarry\3\g_maxGameClients\0\g_maxForceRank\7\g_jediVmerc\0\g_gametype\0\g_forcePowerDisable\0\g_forceBasedTeams\0\g_duelWeaponDisable\1\g_debugMelee\0\fraglimit\20\duel_fraglimit\10\dmflags\0\capturelimit\0\bot_minplayers\0
Logging to security.log
]ICARUS Instance successfully created
target_autosave doesn't have a spawn function
target_autosave doesn't have a spawn function
target_secret doesn't have a spawn function
^1cache failed: roff <kor1/camera1> does not exist or is not a valid roff
trigger_visible doesn't have a spawn function
^3Bot route data not found for kor1
ClientConnect: 0 [x.x.x.x:29070] (NOGUID) "Padawan^7"
broadcast: print "Padawan^7 @@@PLENTER\n"
ClientBegin: 0
^1ERROR: Couldn't spawn NPC sage_of_light
]Segmentation fault
```

Also when this happens there is an error appearing in-game:

`^1File could not be open!`

Note that everything works normally and other NPC's are getting spawned correctly until someone creates a new account or logins into an existing one and there is someone's turn.

The server is running Debian Linux 10 (Buster) 64-bit and was compilled with the following commands:

```
mkdir build && cd build
cmake  -DCMAKE_INSTALL_PREFIX=/home/testzyk/CompilledZyk ..
make
make install
```

Is there any additional content that should be downloaded in order to run Zyk Mod? In this case where it could be obtained?

EDIT:

I just found on jkhub's search that there is a thread exists regarding this mod, but accessing https://jkhub.org/files/file/2306-zyk-openjk-mod/ gives this error:

```
Sorry, there is a problem
We could not locate the item you are trying to view.
Error code: 2D161/2
```

Could you please reupload this content somewhere else?

**Comment by A1Asriel** [comment]
> accessing https://jkhub.org/files/file/2306-zyk-openjk-mod/ gives this error:

I had this error before, Zyk said that it happens when an update is uploaded to the site. When the JKHub staff approves the mod update, the page will be available again.

**Comment by Zyk6870** [comment]
Yes you need the files. Soon they will approve it and the mod will be available for dowbload in JKHub.

**Comment by A1Asriel** [comment]
first issue, btw 😄 and can you tell what with that new branch? a global update?

**Comment by Zyk6870** [comment]
Hi Nikita! The new branch is a new mod I'm making based on this one.
It will be more oriented to PvE quests. :)
